### ISSUE TITLE
SolutionAnalyzer ArrayIndexOutOfBoundsException when VRP contains less activities than vehicles

### ISSUE THREAD

**Issue by jayetc** [graphhopper/jsprit#289] opened 2016-10-24 13:33 UTC
Hi,

I have a problem regarding a simple VRP problem with 2 activities and 9 available vehicles. 
Initialization and searching solution with Jsprit working well, then I got the best solution from all solutions, and then I want to initialize a SolutionAnalyserlike this : 

``` java
analyser = new SolutionAnalyser(vrp, bestSolution, new TransportDistance() {
        @Override
        public double getDistance(jsprit.core.problem.Location from, jsprit.core.problem.Location to) {
            return vrp.getTransportCosts().getTransportCost(from, to, 0., null, null);
        }

  });
```

At this point I got the following exception : 

``` java
java.lang.ArrayIndexOutOfBoundsException: 6
    at jsprit.core.algorithm.state.StateManager.putTypedInternalRouteState(StateManager.java:462)
    at jsprit.core.algorithm.state.UpdateLoads.insertionStarts(UpdateLoads.java:92)
    at jsprit.core.algorithm.state.UpdateLoads.informInsertionStarts(UpdateLoads.java:99)
    at jsprit.core.algorithm.recreate.listener.InsertionListeners.informInsertionStarts(InsertionListeners.java:63)
    at jsprit.core.algorithm.state.StateManager.informInsertionStarts(StateManager.java:568)
    at jsprit.core.analysis.SolutionAnalyser.refreshStates(SolutionAnalyser.java:575)
    at jsprit.core.analysis.SolutionAnalyser.<init>(SolutionAnalyser.java:532)`
```

This exception comes from StateManager class in this method

``` java
<T> void putTypedInternalRouteState(VehicleRoute route, StateId stateId, T state) {
        if (route.isEmpty()) return;
        if(isIndexedBased){
            routeStatesArr[route.getVehicle().getIndex()][stateId.getIndex()] = state;
        }
        else {
            if (!routeStateMap.containsKey(route)) {
                routeStateMap.put(route, new Object[stateIndexCounter]);
            }
            routeStateMap.get(route)[stateId.getIndex()] = state;
        }
    }
```

In fact this line of code **routeStatesArr[route.getVehicle().getIndex()][stateId.getIndex()]**
causes problem be cause routeStatesArr variable is an array of 4 ( initialize with a size of number of activities + 1 ) and [route.getVehicle().getIndex() return 6 -> result ArrayIndexOutOfBoundsException

This issue never appears if the number of activities > number of vehicle.
Thanks in advance for your help.
BR

**Comment by oblonski** [comment] 2016-10-25 10:54
Would you mind to reproduce it in a unit test?

**Comment by jayetc** [comment] 2016-10-26 09:33
Hi,
I tried to write a unit test but without success, I never reproduce the problem but it is always existing in my full code.
After more investigation, the problem seems to come from one custom constraint (HardActivityConstraint) I added to the VRP (with one additional custom StateUpdater for this constraint ).
In fact, if I always returned FULFILLED or always return NOT_FULFILLED, I never have the problem. But If I keep the logic of my constraint I have the ArrayIndexOutOfBoundsException. 
So I am sure I am doing something wrong but no idea for the moment.
Thanks for your help.

**Comment by jayetc** [comment] 2016-10-26 12:16
Hi,

I succeeded to reproduce the problem in a a test case. Please find below the code
`try {
            VehicleRoutingTransportCostsMatrix.Builder costMatrixBuilder = VehicleRoutingTransportCostsMatrix.Builder
                    .newInstance(false);
            costMatrixBuilder.addTransportDistance("Home", "Service1", 10);
            costMatrixBuilder.addTransportDistance("Service1", "Home", 10);

            costMatrixBuilder.addTransportTime("Home", "Service1", 10);
            costMatrixBuilder.addTransportTime("Service1", "Home", 10);
            VehicleRoutingTransportCostsMatrix  costMatrix = costMatrixBuilder.build();

            VehicleRoutingProblem.Builder vrpBuilder = VehicleRoutingProblem.Builder.newInstance()
                    .setRoutingCost(costMatrix).setFleetSize(VehicleRoutingProblem.FleetSize.FINITE);

            for (int i = 0 ; i <10 ; i++) {
                jsprit.core.problem.Location location = jsprit.core.problem.Location.Builder.newInstance().setId("Home").build();
                double cost = 1.;
                if (i == 9) {
                    cost = 0.001;
                }
                VehicleImpl vehicleImpl = VehicleImpl.Builder.newInstance("Vehicle"+i)
                        .setStartLocation(location)
                        .setType(VehicleTypeImpl.Builder.newInstance("VehicleType"+i)
                                .setFixedCost(cost)
                                .setCostPerDistance(cost)
                                .build())
                        .build();
                vrpBuilder = vrpBuilder.addVehicle(vehicleImpl);
            }

            jsprit.core.problem.Location service1Location = jsprit.core.problem.Location.Builder.newInstance()
                    .setId("Service1")
                    .build();
            Service service1 = Service.Builder.newInstance("Service1").
                    setName("Service1").
                    setLocation(service1Location).setServiceTime(10.)
                    .build();
            vrpBuilder = vrpBuilder.addJob(service1);

            VehicleRoutingProblem vrp = vrpBuilder.build();

            VehicleRoutingAlgorithm vra = Jsprit.createAlgorithm(vrp);
            Collection<VehicleRoutingProblemSolution> solutions = vra.searchSolutions();
            VehicleRoutingProblemSolution bestSolution = Solutions.bestOf(solutions);

            SolutionPrinter.print(bestSolution);
            SolutionPrinter.print(vrp, bestSolution, SolutionPrinter.Print.VERBOSE);

            SolutionAnalyser analyser = new SolutionAnalyser(vrp, bestSolution, new TransportDistance() {
                @Override
                public double getDistance(jsprit.core.problem.Location from, jsprit.core.problem.Location to) {
                    return vrp.getTransportCosts().getTransportCost(from, to, 0., null, null);
                }
            });

        } catch (Exception e) {
            e.printStackTrace();
        }`

Could you confirm there is a bug or I am doing something wrong ?
Thanks.
BR

**Comment by jayetc** [comment] 2016-11-02 13:14
Have you succeed to reproduce it with my test case ?

**Comment by oblonski** [comment] 2017-01-10 15:37
I could not reproduce this with your example. It runs perfect. Which jsprit version do you use? The latest master?

**Comment by oblonski** [comment] 2017-01-11 19:32
For the time nobody proves the opposite, I close this.

**Closed by oblonski** 2017-01-11 19:32 UTC
Labels: bug
