### ISSUE TITLE
GraphStreamViewer is not working with breaks

### ISSUE THREAD

**Issue by mschiess** [graphhopper/jsprit#226] opened 2016-04-06 14:21 UTC
Hi,

I simply added 
`new GraphStreamViewer(problem, bestSolution).labelWith(Label.ID).setRenderDelay(200).display();`
at the end of the BreakExample and I got the following exception
`Exception in thread "main" org.graphstream.graph.ElementNotFoundException: Cannot create edge 1.2[4_[x=15.0][y=13.0]->myFirstBreak_[x=15.0][y=7.0]]. Node 'myFirstBreak_[x=15.0][y=7.0]' does not exist.
at org.graphstream.graph.implementations.AbstractGraph.addEdge(AbstractGraph.java:872)
at org.graphstream.graph.implementations.AbstractGraph.addEdge(AbstractGraph.java:352)
at com.graphhopper.jsprit.analysis.toolbox.GraphStreamViewer.renderRoute(GraphStreamViewer.java:589)
at com.graphhopper.jsprit.analysis.toolbox.GraphStreamViewer.render(GraphStreamViewer.java:398)
at com.graphhopper.jsprit.analysis.toolbox.GraphStreamViewer.display(GraphStreamViewer.java:328)
at com.graphhopper.jsprit.examples.BreakExample.main(BreakExample.java:108)`

**Comment by oblonski** [comment] 2016-04-06 14:27
:+1: will fix this asap

**Comment by agentbug** [comment] 2016-05-04 07:41
Hi, I've got a problem too, 
new GraphStreamViewer(problem,bestSolution).display();

and I do not hava any Break but:

CAUSE java.lang.reflect.InvocationTargetException :: null 
ROOT CAUSE MESSAGE: Cannot create edge 1.2[shipment2_[x=3.0][y=4.0]->shipment1_[x=3.0][y=4.0]]. Node 'shipment1_[x=3.0][y=4.0]' does not exist. 
     This happens around this area in your code.

**Comment by oblonski** [comment] 2016-11-22 16:00
fixed via https://github.com/graphhopper/jsprit/commit/0cbfb72d8d367c401d10d95ff9aa523d0198af7a
currently only available in https://github.com/graphhopper/jsprit/tree/job-activity-refactoring

**Closed by oblonski** 2016-11-22 16:00 UTC
Labels: bug
